baseURL = 'https://seiken-lab.github.io/JSB01_web/'
languageCode = 'ja'
# paginate = 5
pygmentsUseClasses = true
title = 'JSB01'

[module]
[[module.imports]]
path = 'github.com/adityatelange/hugo-PaperMod'

[markup]
[markup.highlight]
noClasses = false

[menu]

[[menu.main]]
identifier = 'feature'
name = '特徴'
url = '/feature/'
weight = 10

[[menu.main]]
identifier = 'usage'
name = '使い方'
url = '/usage/'
weight = 20

[[menu.main]]
identifier = 'specification'
name = '製品仕様'
url = '/specification/'
weight = 30

[[menu.main]]
identifier = 'purchase'
name = 'ご購入'
url = '/purchase/'
weight = 40

[[menu.main]]
identifier = 'blog'
name = 'blog'
url = '/blog/'
weight = 100

[[menu.main]]
identifier = 'developers'
name = '開発者情報'
url = '/developers/'
weight = 200

[minify]
disableXML = true
minifyOutput = true

[params]
DateFormat = 'January 2, 2006'
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowPostNavLinks = false
ShowReadingTime = false
ShowRssButtonInSectionTermList = false
ShowShareButtons = false
ShowWordCount = false
UseHugoToc = true
# author = 'Me'
comments = false
defaultTheme = 'auto'
description = 'JSB01 is a device that assists visually impaired people to walk safely using an ultrasonic sensor.'
disableScrollToTop = true
disableSpecial1stPost = false
disableThemeToggle = false
env = 'production'
hideSummary = false
hidemeta = true
# images = ['<link or path of image for opengraph, twitter-cards>']
# keywords = ['Blog', 'Portfolio', 'PaperMod']
showtoc = false
title = 'JSB01'
tocopen = false

# [params.analytics]
# [params.analytics.bing]
# SiteVerificationTag = 'XYZabc'

# [params.analytics.google]
# SiteVerificationTag = 'XYZabc'

# [params.analytics.yandex]
# SiteVerificationTag = 'XYZabc'

# [params.assets]
# apple_touch_icon = '<link / abs url>'
# favicon = '<link / abs url>'
# favicon16x16 = '<link / abs url>'
# favicon32x32 = '<link / abs url>'
# safari_pinned_tab = '<link / abs url>'

# [params.cover]
# hidden = true
# hiddenInList = true
# hiddenInSingle = true

[params.editPost]
Text = 'Suggest Changes'
URL = 'https://github.com/<path_to_repo>/content'
appendFilePath = true

[params.fuseOpts]
distance = 1000
isCaseSensitive = false
keys = ['title', 'permalink', 'summary', 'content']
limit = 10
location = 0
minMatchCharLength = 0
shouldSort = true
threshold = 0.4

# [params.homeInfoParams]
Content = 'Welcome to JSB01 website'
Title = 'Hi there 👋'

# [params.label]
# icon = '/apple-touch-icon.png'
# iconHeight = 35
# text = 'Home'

# [params.profileMode]
# enabled = false
# imageHeight = 120
# imageTitle = 'my image'
# imageUrl = '<img location>'
# imageWidth = 120
# subtitle = 'This is subtitle'
# title = 'ExampleSite'

# [[params.profileMode.buttons]]
# name = 'Posts'
# url = 'posts'

# [[params.profileMode.buttons]]
# name = 'Tags'
# url = 'tags'

# [[params.socialIcons]]
# name = 'x'
# url = 'https://x.com/'

# [[params.socialIcons]]
# name = 'stackoverflow'
# url = 'https://stackoverflow.com'

# [[params.socialIcons]]
# name = 'github'
# url = 'https://github.com/'
